# Generated by Django 5.2.7 on 2025-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ogloszeniafirm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(blank=True, choices=[('NL', 'Holandia / Netherlands'), ('PL', 'Polska / Poland'), ('DE', 'Niemcy / Germany'), ('CZ', 'Czechy / Czech Republic'), ('BG', 'Bułgaria / Bulgaria'), ('SK', 'Słowacja / Slovakia'), ('UA', 'Ukraina / Ukraine'), ('OTHER', 'Inny kraj / Other country')], max_length=50, null=True, verbose_name='Kraj / Country'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='remote_option',
            field=models.CharField(blank=True, choices=[('ONSITE', 'Na miejscu / On-site / Op locatie'), ('REMOTE', 'Zdalna / Remote / Op afstand'), ('HYBRID', 'Hybrydowa / Hybrid / Hybride')], default='ONSITE', max_length=50, null=True, verbose_name='Praca zdalna / Remote option'),
        ),
    ]
