# Generated by Django 5.2.7 on 2025-10-22 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, choices=[('PRODUCTION', 'Production / Produkcja'), ('AGRICULTURE', 'Agriculture / Rolnictwo'), ('CLEANING', 'Cleaning / Sprzątanie'), ('CONSTRUCTION', 'Construction / Budownictwo'), ('LOGISTICS', 'Logistics / Transport'), ('DRIVERS', 'Drivers / Kierowcy'), ('HEALTHCARE', 'Healthcare / Opieka'), ('FINANCE', 'Finance / Finanse'), ('ADMINISTRATION', 'Administration / Administracja'), ('TECHNICAL', 'Technical / Techniczne'), ('IT', 'IT / Informatyka'), ('HORECA', 'Horeca / Gastronomia'), ('ENERGY', 'Energy / Energetyka'), ('MARKETING', 'Marketing / PR'), ('SALES', 'Sales / Sprzedaż'), ('HR', 'HR / Szkolenia'), ('RND', 'R&D / Badania'), ('OTHER', 'Other / Inne')], max_length=50, null=True)),
                ('job_role', models.CharField(blank=True, choices=[('CARPENTER', 'Carpenter / Timmerman / Stolarz / Tischler / Truhlář / Дърводелец / Столяр / Деревороб'), ('MASON', 'Mason / Metselaar / Murarz / Maurer / Zedník / Каменоделец / Каменар / Каменяр'), ('CONSTRUCTION_HELPER', 'Construction Helper / Bouwhelper / Pomocnik budowlany / Bauhelfer / Строителен помощник / Будівельний помічник'), ('PAINTER', 'Painter / Schilder / Malarz / Maler / Malíř / Бояджия / Маляр'), ('PLASTERER', 'Plasterer / Stukadoor / Tynkarz / Stuckateur / Štuk / Тенекеджия / Штукатур'), ('PLUMBER', 'Plumber / Loodgieter / Hydraulik / Klempner / Instalatér / Водопроводчик / Водопровідник'), ('ELECTRICIAN', 'Electrician / Elektricien / Elektryk / Elektriker / Elektrikář / Ел. техник / Електрик'), ('WINDOW_INSTALLER', 'Window Installer / Raammonteur / Monter okien / Fensterbauer / Montér oken / Монтажник на прозорци / Монтажник вікон'), ('FAÇADE_INSTALLER', 'Facade Installer / Gevelmonteur / Monter fasad / Fassadenmonteur / Montér fasád / Монтажник на фасади / Монтажник фасадів'), ('TECHNICIAN', 'Technician / Technicus / Technik / Techniker / Техник / Технік'), ('PRODUCTION_WORKER', 'Production Worker / Productiemedewerker / Pracownik produkcji / Produktionsmitarbeiter / Výrobní pracovník / Працівник виробництва'), ('PHYSICAL_WORKER', 'Physical Worker / Fysiek werker / Pracownik fizyczny / Hilfsarbeiter / Фізичний працівник'), ('OPERATOR', 'Machine Operator / Operator maszyn / Obsluha strojů / Машинен оператор'), ('DRIVER', 'Driver / Chauffeur / Kierowca / Fahrer / Шофьор / Водій'), ('CLEANER', 'Cleaner / Schoonmaker / Pracownik sprzątający / Reiniger / Uklízeč / Прибиральник'), ('BUILDER', 'Construction Worker / Bouwer / Budowniczy / Bauarbeiter / Строител / Будівельник'), ('MECHANIC', 'Mechanic / Monteur / Mechanik / Mechaniker / Механік'), ('NURSE', 'Nurse / Verpleegkundige / Pielęgniarka / Krankenschwester / Zdravotní sestra / Медсестра'), ('ACCOUNTANT', 'Accountant / Boekhouder / Księgowy / Buchhalter / Счетоводител / Бухгалтер'), ('CHEF', 'Chef / Kok / Kucharz / Küchenchef / Šéfkuchař / Готвач / Шеф-кухар'), ('IT_SPECIALIST', 'IT Specialist / IT-specialist / Specjalista IT / IT-Spezialist / IT спеціаліст'), ('OTHER', 'Other / Overig / Inny / Други / Інше')], max_length=50, null=True)),
                ('desired_position', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('available_for_contact', models.BooleanField(default=False)),
                ('worked_in_eu', models.BooleanField(default=False)),
                ('worked_in_nl', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('EN', 'English'), ('DE', 'German / Deutsch'), ('NL', 'Dutch / Nederlands'), ('PL', 'Polish / Polski'), ('RU', 'Russian / Русский'), ('CS', 'Czech / Česky'), ('BG', 'Bulgarian / Български'), ('UA', 'Ukrainian / Українська')], max_length=10)),
                ('level', models.CharField(choices=[('BASIC', 'Basic / Podstawowy'), ('INTERMEDIATE', 'Intermediate / Średni'), ('ADVANCED', 'Advanced / Zaawansowany')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('year_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('PL', 'Poland / Polska'), ('NL', 'Netherlands / Holandia'), ('EU', 'Other EU / Inna UE')], max_length=50)),
                ('is_vca', models.BooleanField(default=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_in_profession', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(choices=[('PL', 'Poland / Polska'), ('NL', 'Netherlands / Holandia'), ('EU', 'Other EU / Inna UE')], max_length=50)),
                ('position_description', models.CharField(blank=True, max_length=200, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_experiences', to='candidates.candidate')),
            ],
        ),
    ]
