# Generated by Django 5.2.7 on 2025-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job_role',
            field=models.CharField(blank=True, choices=[('CARPENTER', 'Carpenter / Timmerman / Stolarz / Tischler / Truhlář / Дърводелец / Столяр / Деревороб'), ('MASON', 'Mason / Metselaar / Murarz / Maurer / Zedník / Каменоделец / Каменар / Каменяр'), ('CONSTRUCTION_HELPER', 'Construction Helper / Bouwhelper / Pomocnik budowlany / Bauhelfer / Строителен помощник / Будівельний помічник'), ('PAINTER', 'Painter / Schilder / Malarz / Maler / Malíř / Бояджия / Маляр'), ('PLASTERER', 'Plasterer / Stukadoor / Tynkarz / Stuckateur / Štuk / Тенекеджия / Штукатур'), ('PLUMBER', 'Plumber / Loodgieter / Hydraulik / Klempner / Instalatér / Водопроводчик / Водопровідник'), ('ELECTRICIAN', 'Electrician / Elektricien / Elektryk / Elektriker / Elektrikář / Ел. техник / Електрик'), ('WELDER', 'Welder / Lasser / Spawacz / Schweißer / Svářeč / Зварник / Зварювальник'), ('WINDOW_INSTALLER', 'Window Installer / Raammonteur / Monter okien / Fensterbauer / Montér oken / Монтажник на прозорци / Монтажник вікон'), ('FAÇADE_INSTALLER', 'Facade Installer / Gevelmonteur / Monter fasad / Fassadenmonteur / Montér fasád / Монтажник на фасади / Монтажник фасадів'), ('TECHNICIAN', 'Technician / Technicus / Technik / Techniker / Техник / Технік'), ('PRODUCTION_WORKER', 'Production Worker / Productiemedewerker / Pracownik produkcji / Produktionsmitarbeiter / Výrobní pracovník / Працівник виробництва'), ('PHYSICAL_WORKER', 'Physical Worker / Fysiek werker / Pracownik fizyczny / Hilfsarbeiter / Фізичний працівник'), ('OPERATOR', 'Machine Operator / Operator maszyn / Obsluha strojů / Машинен оператор'), ('DRIVER', 'Driver / Chauffeur / Kierowca / Fahrer / Шофьор / Водій'), ('CLEANER', 'Cleaner / Schoonmaker / Pracownik sprzątający / Reiniger / Uklízeč / Прибиральник'), ('BUILDER', 'Construction Worker / Bouwer / Budowniczy / Bauarbeiter / Строител / Будівельник'), ('MECHANIC', 'Mechanic / Monteur / Mechanik / Mechaniker / Механік'), ('NURSE', 'Nurse / Verpleegkundige / Pielęgniarka / Krankenschwester / Zdravotní sestra / Медсестра'), ('ACCOUNTANT', 'Accountant / Boekhouder / Księgowy / Buchhalter / Счетоводител / Бухгалтер'), ('CHEF', 'Chef / Kok / Kucharz / Küchenchef / Šéfkuchař / Готвач / Шеф-кухар'), ('IT_SPECIALIST', 'IT Specialist / IT-specialist / Specjalista IT / IT-Spezialist / IT спеціаліст'), ('OTHER', 'Other / Overig / Inny / Други / Інше')], max_length=50, null=True),
        ),
    ]
