"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os

# ----------------------------------------
# Ścieżki
# ----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------
# Bezpieczeństwo
# ----------------------------------------
# In production we recommend setting SECRET_KEY in environment variable DJANGO_SECRET_KEY
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-f1if(8j!4p9j9jx0=*3z38b^d78xcu8#2#19cvmw^o3^6!1pgx')
# Keep DEBUG=True for local development. In production set DJANGO_DEBUG=false (or set DEBUG=False here).
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'
# Allowed hosts: replace with your real domains in production or set DJANGO_ALLOWED_HOSTS env (comma-separated)
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,job.hrconsultingpartner.nl,www.job.hrconsultingpartner.nl').split(',')

# ----------------------------------------
# Aplikacje
# ----------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'candidates',        # aplikacja kandydatów
    'Ogloszeniafirm',    # aplikacja ofert pracy
]

# ----------------------------------------
# Middleware
# ----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise middleware for serving static files in production without extra server config
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

# ----------------------------------------
# Templates
# ----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # <- warto mieć wspólny katalog templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# ----------------------------------------
# Bazy danych – dwie oddzielne
# ----------------------------------------
DATABASES = {
    'default': {  # baza kandydatów
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'candidates.sqlite3',  # lepsza, opisowa nazwa
    },
    'jobs_db': {  # baza ofert pracy
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'ogloszeniafirm.sqlite3',
    }
}

# Router baz danych (musi wskazywać na plik dbrouters.py)
DATABASE_ROUTERS = ['myproject.dbrouters.JobsRouter']

# ----------------------------------------
# Walidacja haseł
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------
# Internacjonalizacja
# ----------------------------------------
LANGUAGE_CODE = 'pl'
TIME_ZONE = 'Europe/Warsaw'
USE_I18N = True
USE_TZ = True

# ----------------------------------------
# Statyczne pliki
# ----------------------------------------
# Gdzie trafią zebrane pliki statyczne po `collectstatic` (ustawić na serwerze)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Use WhiteNoise storage backend to serve compressed static files (helps on simple hosts)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ----------------------------------------
# Domyślny typ pola klucza głównego
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

